# Generated by Django 3.2.16 on 2023-01-27 05:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('name', models.CharField(max_length=50, verbose_name='course name')),
                ('desc', models.CharField(max_length=300, verbose_name='course description')),
                ('duration', models.IntegerField(default=0, verbose_name='duration of the course(mins)')),
                ('difficulty', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('hard', 'hard')], max_length=12, verbose_name='difficulty')),
                ('number_of_students', models.IntegerField(default=0, verbose_name='number of students')),
                ('number_of_beFav', models.IntegerField(default=0, verbose_name='number of students who intended to take the course')),
                ('number_of_clicks', models.IntegerField(default=0, verbose_name='number_of_clicks')),
                ('category', models.CharField(max_length=20, verbose_name='category')),
                ('tag', models.CharField(max_length=10, verbose_name='course tag')),
                ('shoud_know', models.CharField(default='', max_length=300, verbose_name='should know ahead taking the course')),
                ('teacher_desc', models.CharField(default='', max_length=300, verbose_name='what the teacher wants to say')),
                ('course_detail', models.TextField(verbose_name="course's details")),
                ('Images', models.ImageField(upload_to='courses/%Y/%m', verbose_name='img')),
            ],
            options={
                'verbose_name': 'Class info',
                'verbose_name_plural': 'Class info',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('name', models.CharField(max_length=100, verbose_name='lesson name')),
                ('duration', models.IntegerField(default=0, verbose_name='duration of the lesson(mins)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Lesson info',
                'verbose_name_plural': 'Lesson info',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('name', models.CharField(max_length=100, verbose_name='video name')),
                ('duration', models.IntegerField(default=0, verbose_name='duration of the video(mins)')),
                ('url', models.CharField(max_length=200, verbose_name='video url')),
                ('Lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='sections')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
            },
        ),
        migrations.CreateModel(
            name='CourseResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('file', models.FileField(max_length=200, upload_to='course/resources/%y/%m', verbose_name='downloading address')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'course resources',
                'verbose_name_plural': 'course resources',
            },
        ),
    ]
