# Generated by Django 3.2.16 on 2023-03-31 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20230328_2016'),
        ('courses', '0002_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organizations.instructors', verbose_name='teacher'),
        ),
    ]
