# Generated by Django 3.2.16 on 2023-03-31 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
