# Generated by Django 3.2.16 on 2023-04-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='announcement',
            field=models.CharField(default='', max_length=300, verbose_name='course announcement'),
        ),
    ]
