# Generated by Django 3.2.16 on 2023-01-27 05:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('name', models.CharField(max_length=20, verbose_name='user name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('course_name', models.CharField(max_length=50, verbose_name='course_name')),
            ],
            options={
                'verbose_name': 'UserConsultation',
                'verbose_name_plural': 'UserConsultation',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('message', models.CharField(max_length=200, verbose_name='contents')),
                ('has_read', models.BooleanField(default=False, verbose_name='whether the message has been read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user info')),
            ],
            options={
                'verbose_name': 'user message',
                'verbose_name_plural': 'user message',
            },
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('fav_id', models.IntegerField(verbose_name='type id')),
                ('fav_type', models.IntegerField(choices=[(1, 'course'), (2, 'instruction'), (3, 'instructor')], default=1, verbose_name='收藏类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user favorites',
                'verbose_name_plural': 'user favorites',
            },
        ),
        migrations.CreateModel(
            name='UserCourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user course relation',
                'verbose_name_plural': 'user course relation',
            },
        ),
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('comments', models.CharField(max_length=200, verbose_name='comments')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user info')),
            ],
            options={
                'verbose_name': 'comments on the course',
                'verbose_name_plural': 'comments on the course',
            },
        ),
    ]
