# Generated by Django 3.2.16 on 2023-03-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'verbose_name': 'comments', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='userconsultation',
            options={'verbose_name': 'User Consultation', 'verbose_name_plural': 'User Consultation'},
        ),
    ]
