# Generated by Django 3.2.16 on 2023-01-27 05:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the organization')),
                ('desc', models.TextField(max_length=10, verbose_name='Description')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='Organization tag')),
                ('category', models.CharField(choices=[('Study channel', 'Study channel'), ('Instructions', 'Instructions'), ('Schools', 'Schools')], max_length=20, verbose_name='category')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of clicks')),
                ('number_of_beFav', models.IntegerField(default=0, verbose_name='number of students who likes the organization')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo')),
                ('number_of_students', models.IntegerField(default=0, verbose_name='number of students')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('number_of_courses', models.IntegerField(default=0, verbose_name='num of courses')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='course added time')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the instructor')),
                ('work_years', models.IntegerField(default=0, verbose_name='years of work')),
                ('work_company', models.CharField(max_length=50, verbose_name='company')),
                ('work_position', models.CharField(max_length=50, verbose_name='position')),
                ('points', models.CharField(max_length=50, verbose_name='characteristic')),
                ('click_nums', models.IntegerField(default=0, verbose_name='num of clicks')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='number of been collected')),
                ('age', models.IntegerField(default=18, verbose_name='age')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='profile photo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations', verbose_name='From org')),
            ],
            options={
                'verbose_name': 'name of the instructor',
                'verbose_name_plural': 'name of the instructor',
            },
        ),
    ]
