# Generated by Django 3.2.16 on 2023-03-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20230320_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='web_url',
            field=models.TextField(default='', max_length=200, verbose_name='WebUrl'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='desc',
            field=models.TextField(default='', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='Organization tag'),
        ),
    ]
