# Generated by Django 3.2.16 on 2023-04-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20230328_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='desc',
            field=models.TextField(default='', max_length=5000, verbose_name='Description'),
        ),
    ]
