# Generated by Django 3.2.16 on 2023-04-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizations_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='desc_short',
            field=models.TextField(default='', max_length=200, verbose_name='Description'),
        ),
    ]
