# Generated by Django 3.2.16 on 2023-04-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizations_desc_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='desc_short',
            field=models.TextField(default='', max_length=200, verbose_name='ShortDescription'),
        ),
    ]
