# Generated by Django 3.2.16 on 2023-04-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organizations_desc_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='age',
        ),
        migrations.RemoveField(
            model_name='instructors',
            name='points',
        ),
        migrations.RemoveField(
            model_name='instructors',
            name='work_company',
        ),
        migrations.RemoveField(
            model_name='instructors',
            name='work_years',
        ),
        migrations.AddField(
            model_name='instructors',
            name='desc',
            field=models.TextField(default='', max_length=5000, verbose_name='Description'),
        ),
    ]
